TOP_PLACEMENT_SPECIFICATION = "TOP"
BOTTOM_PLACEMENT_SPECIFICATION = "BOTTOM"
LEFT_PLACEMENT_SPECIFICATION = "LEFT"
RIGHT_PLACEMENT_SPECIFICATION = "RIGHT"
HPAD_SPECIFICATION = 32
VPAD_SPECIFICATION = 32